import type { Metadata } from 'next';
import './globals.css';
import AppShell from '../components/AppShell';
import AuthProvider from '../components/AuthProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='min-h-screen bg-background text-foreground font-sans'>
				<AuthProvider>
					<AppShell>{children}</AppShell>
				</AuthProvider>
			</body>
		</html>
	);
}
